[package]
name = "my_library"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra = { version = "0.32", features = ["serde-serialize"] }
num-complex = "0.4"
nalgebra-lapack = "0.24"
lapack = "0.19"
plotters = "0.3"
